# Generated by Django 3.1.2 on 2021-03-06 12:43

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blank', upload_to=posts.models.get_upload_post_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='posts.task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='files',
            field=models.FileField(upload_to=posts.models.get_upload_result_path),
        ),
        migrations.AlterField(
            model_name='task',
            name='files',
            field=models.FileField(upload_to=posts.models.get_upload_task_path),
        ),
    ]
