# Generated by Django 3.1.2 on 2021-04-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileeducation',
            name='title',
            field=models.CharField(default='kebab', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='profileskill',
            unique_together={('skill_id', 'profile')},
        ),
    ]
