# Generated by Django 3.1.2 on 2021-03-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210306_1243'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('post_id', 'title')},
        ),
    ]
