# Generated by Django 3.1.2 on 2021-05-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ends',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_role_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='salary_high',
        ),
        migrations.RemoveField(
            model_name='post',
            name='salary_low',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tasks_summary',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.DeleteModel(
            name='PostSkill',
        ),
    ]
