# Generated by Django 3.1.2 on 2021-05-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210508_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
