# Generated by Django 3.1.2 on 2021-04-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210426_1100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskTag',
            new_name='TaskSkill',
        ),
    ]
