# Generated by Django 3.1.2 on 2021-03-17 20:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20210317_1933'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('author_id', 'task_id')},
        ),
    ]
