# Generated by Django 3.1.2 on 2021-05-08 10:38

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_task_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.FileField(blank=True, null=True, upload_to=posts.models.get_upload_task_path)),
            ],
        ),
    ]
