# Generated by Django 3.1.2 on 2021-05-10 17:12

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_testfileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testfileupload',
            name='code',
            field=models.FileField(blank=True, null=True, upload_to=posts.models.get_upload_test_path),
        ),
    ]
