# Generated by Django 3.1.2 on 2021-04-27 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210427_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postskill',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='profileskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_skills', to='posts.skill'),
        ),
        migrations.AlterField(
            model_name='taskskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_skills', to='posts.skill'),
        ),
        migrations.AlterField(
            model_name='taskskill',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='posts.task'),
        ),
    ]
