# Generated by Django 3.1.2 on 2021-05-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210510_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileexperience',
            name='description',
        ),
        migrations.AddField(
            model_name='profileexperience',
            name='title',
            field=models.CharField(default='kebab', max_length=100),
            preserve_default=False,
        ),
    ]
