# Generated by Django 3.1.2 on 2021-04-28 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210427_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskskill',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_skills', to='posts.task'),
        ),
    ]
