# Generated by Django 3.1.2 on 2021-04-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210428_0756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskSkill',
        ),
    ]
