# Generated by Django 3.1.2 on 2021-03-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresettoken',
            old_name='activation_token',
            new_name='reset_token',
        ),
    ]
