# Generated by Django 3.1.2 on 2021-03-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_auto_20210303_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company',
        ),
    ]
