# Generated by Django 3.1.2 on 2021-03-18 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_customuser_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company',
        ),
    ]
